### PR TITLE
Add initial tests

### LINKED ISSUE #7: Add tests
Add in the tests and ensure they run properly with `npm test`. Tests should be contained within the `test/` folder, and should be suffixed with `.test.ts` to work.

Enzyme and Puppeteer are available for use in tests, which are run by Jest.

### PR DESCRIPTION
**Pull request by corymharper**
Closes #7

### CODE REVIEW

**Comment by WesCossick** [comment]
By the way "dropdown" is misspelled in some of the file names.

**Comment by WesCossick** [comment]
@corymharper pull the latest commits; the tests all pass. The Jest docs state that `jsdom` is the default test environment, yet adding `jsdom` explicitly fixed the problem.



Turns out `jsdom` is not _actually_ the default.

**Comment by corymharper** [comment]
I was along the same line of thought, but I think jsdom _is_ actually the default, but our preset: "jest-puppeteer" overrules that default with a test environment for puppeteer. I confirmed this by removing [line #76](https://github.com/sparksuite/react-accessible-dropdown-menu-hook/blob/master/package.json#L76), however since we would like to use puppeteer, I think we probably need to use a newer config option they have, [projects](https://jestjs.io/docs/en/configuration.html#projects-arraystring--projectconfig).

**Comment by WesCossick** [comment]
Ah, you're right. It looks like now tests with Puppeteer fail because that environment is missing.

**Comment by WesCossick** [comment]
Fixed!

**Pull request merged**
